const players = [
  {
    player_id: 1,
    id_user: 1,
    team_id: 1,
    name: 'Benny Bell',
    image: 'futsal/w5loukgjpjmk6npkrwvd',
    confirmation: 'present',
    position: 'striker',
    goals: 8,
    likes: 53,
    weigh: '60 kg',
    height: '1.20 m',
  },
  {
    player_id: 2,
    id_user: 1,
    team_id: 1,
    name: 'Corban Neville',
    image: 'futsal/jzpltyqjyxx5tstkvvrd',
    confirmation: 'present',
    position: 'goalkeeper',
    goals: 8,
    likes: 584,
    weigh: '55kg',
    height: '1.50m',
  },
  {
    player_id: 3,
    id_user: 1,
    team_id: 1,
    name: 'Richard Mina Mina',
    image: 'futsal/ju8cl42kzvqk6jsukfka',
    confirmation: 'present',
    position: 'Right wing',
    goals: 7,
    likes: 40,
    weigh: '58kg',
    height: '1.70m',
  },
  {
    player_id: 6,
    id_user: 1,
    team_id: 1,
    name: 'Jaime Marleau',
    image: 'futsal/hwunlimponiwgmmegwv7',
    confirmation: 'present',
    position: 'Right wing',
    goals: 10,
    likes: 44,
    weigh: '70kg',
    height: '1.70m',
  },
  {
    player_id: 29,
    id_user: 1,
    team_id: 2,
    name: 'Mark Whelly',
    image: 'futsal/uypc0maqu9qc4smnuuw2',
    confirmation: 'present',
    position: 'Striker',
    goals: 0,
    likes: 8,
    weigh: '60kg',
    height: '1.6m',
  },
  {
    player_id: 34,
    id_user: 1,
    team_id: 5,
    name: 'Luciana Huerta',
    image: 'futsal/zuv21t2smd4rdqysaywe',
    confirmation: 'present',
    position: 'Striker',
    goals: 0,
    likes: 5,
    weigh: '25kg',
    height: '1.20 m',
  },
  {
    player_id: 35,
    id_user: 1,
    team_id: 2,
    name: 'Harrison Shaffer',
    image: 'futsal/hebnv2rv7uh6vyfblqjp',
    confirmation: 'present',
    position: 'Defense',
    goals: 0,
    likes: 0,
    weigh: '25 kg',
    height: '1.20 m',
  },
  {
    player_id: 36,
    id_user: 1,
    team_id: 2,
    name: 'Karina Nolan',
    image: 'futsal/k6eek2zpva7cblslr4lw',
    confirmation: 'present',
    position: 'Goalkeeper',
    goals: 0,
    likes: 0,
    weigh: '60 kg',
    height: '1.50 m',
  },
  {
    player_id: 37,
    id_user: 1,
    team_id: 2,
    name: 'Genaro Jennings',
    image: 'futsal/roqr64vwffbaa63jaaxn',
    confirmation: 'present',
    position: 'Right wing',
    goals: 0,
    likes: 0,
    weigh: '35 kg',
    height: '1.45 m',
  },
  {
    player_id: 38,
    id_user: 1,
    team_id: 2,
    name: 'Felix Atkins',
    image: 'futsal/s1zjq7r8v8ey4hd5b4wv',
    confirmation: 'present',
    position: 'Left Wing',
    goals: 0,
    likes: 4,
    weigh: '35 kg',
    height: '1.65m',
  },
  {
    player_id: 46,
    id_user: 1,
    team_id: 5,
    name: 'Patricio Huerta',
    image: 'futsal/ac9ffid1l55c1qapr13d',
    confirmation: 'present',
    position: 'Striker',
    goals: 0,
    likes: 0,
    weigh: '60kg',
    height: '1.20m',
  },
  {
    player_id: 47,
    id_user: 1,
    team_id: 5,
    name: 'Niko Guerra',
    image: 'futsal/ddumworjwqlzhdp6dgkl',
    confirmation: 'present',
    position: 'Defense',
    goals: 0,
    likes: 0,
    weigh: '60kg',
    height: '1.20m',
  },
  {
    player_id: 48,
    id_user: 1,
    team_id: 7,
    name: 'Winston Lewis',
    image: 'futsal/jeutwcwdqodbwveivaa7',
    confirmation: 'present',
    position: 'Striker',
    goals: 0,
    likes: 0,
    weigh: '60kg',
    height: '1.20m',
  },
  {
    player_id: 49,
    id_user: 1,
    team_id: 6,
    name: 'Mai Escobar',
    image: 'futsal/rupxobwoxbouqipaf0un',
    confirmation: 'present',
    position: 'Defense',
    goals: 0,
    likes: 0,
    weigh: '35 kg',
    height: '1.6m',
  },
  {
    player_id: 50,
    id_user: 1,
    team_id: 1,
    name: 'Patricio Huerta',
    image: 'futsal/mfwbqbauw3lnmfaxcfzc',
    confirmation: 'present',
    position: 'Striker',
    goals: 0,
    likes: 0,
    weigh: '60kg',
    height: '1.20m',
  },
];

module.exports = { players };
